# begin action.yml
name: 'Gemini Python Tutor'
description: 'Action to generate feedback using LLMs'
inputs:
  report-files:
    description: 'Comma-separated list of test report file paths'
    required: true
  student-files:
    description: 'Comma-separated list of student code file paths'
    required: true
  api-key:
    description: 'API key for the selected LLM'
    required: true
  model:
    description: 'LLM model to use (e.g., gemini, grok)'
    required: false
    default: 'gemini'
  readme-path:
    description: 'Path to the README file with assignment instructions'
    required: true
  explanation-in:
    description: 'Language for explanations (e.g., English, Korean)'
    required: false
    default: 'English'
  fail-expected:
    description: 'Whether test failures are expected (true/false)'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
# end action.yml
