# Make sure to change the action name here (must be unique).
# Update the rest as needed.
name: 'gemini-python-tutor'
description: 'Gemini Python Tutor for Github Classroom Assignments'
branding: # Look at documentation for branding options/requirements. These are my favorites.
  icon: 'book-open'
  color: 'green'
inputs:
  report-files:  
    description: 'Comma-separeted list of json report file paths'
    required: false
    default: 'report.json'
  python-code-path:
    description: 'python code path'
    required: false
    default: 'exercise.py'
  readme-path:
    description: 'assignment instructions path'
    required: false
    default: 'README.md'
outputs:
  feedback:
    description: 'Feedback from the tutor'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input-one }}
    - ${{ inputs.input-two }}
