# Make sure to change the action name here (must be unique).
# Update the rest as needed.
name: 'gemini-python-tutor'
description: 'Gemini Python Tutor for Github Classroom Assignments'
branding: # Look at documentation for branding options/requirements. These are my favorites.
  icon: 'book-open'
  color: 'green'
inputs:
  report-files:
    description: 'Comma-separeted list of json report file paths'
    required: true
    default: 'report.json'
    type: list
  student-files:
    description: 'Comma-separated list of student's Python file paths or a glob pattern'
    required: false
    default: 'exercise.py'
    type: list
  readme-path:
    description: 'assignment instructions path'
    required: false
    default: 'README.md'
    type: string
outputs:
  feedback:
    description: 'Feedback from the tutor'
runs:
  using: 'docker'
  image: 'Dockerfile'
